### ISSUE TITLE
Change coding style for argparse

### ISSUE THREAD

**Issue by p-ranav** [p-ranav/argparse#133]
* Change private member variable names to be (1) underscore separated, (2) all lower case, (3) with a trailing underscore, e.g., `my_private_variable_` instead of `mMyPrivateVariable`.
* Change member function names to be (1) underscore separated, (2) all lower case, (3) with a trailing underscore if the member function is private, e.g., `my_public_member_function()`, and `my_private_member_function_()`
* Change function parameter names to be (1) underscore separated, (2) all lower case, e.g., `my_function(int foo, float bar)`
* Class names will be PascalCase, e.g., `ArgumentParser`
* Add `clang-format` configuration and use the standard LLVM coding style 

From:
```cpp
  std::vector<std::string> mNames;
  std::string_view mUsedName;
```

To:

```cpp
  std::vector<std::string> names_;
  std::string_view used_name_;
```

**Comment by p-ranav** [comment]
I'm okay with `m_` prefix for member variables. I'm also okay with no special naming of private member functions since I agree with your points. I'm not particularly bothered by the mixed use of `class` and `struct` - the naming style was meant for both classes and structs. In your experience, is there a reason to treat structs and classes (w.r.t naming style) differently?

Additionally, I've been wanting to break `argparse.hpp` into a handful of smaller header files - can generate the single header version (like [here](https://github.com/p-ranav/indicators)). That would seriously improve readability and maintainability of the source.

**Comment by skrobinson** [comment]
> I'm not particularly bothered by the mixed use of class and struct - the naming style was meant for both classes and structs. In your experience, is there a reason to treat structs and classes (w.r.t naming style) differently?

When first reading `argparse.hpp`, I noticed how the structs seemed to be "active", while the two classes model objects. The style conventions (snake_case vs PascalCase) raised my awareness of this difference. I just found it an interesting split, but I do not have a preference either way.

> Additionally, I've been wanting to break argparse.hpp into a handful of smaller header files

As long as a single-file version is available without user processing, I don't see a problem. I've never worked with a split header project so I don't see the benefit. Could you explain how it helps?

**Comment by skrobinson** [comment]
First, would this discussion be better on a Wiki page so that there is one copy of the most current style guide?

Proposed final checks:

```yaml
Checks:
  -*,
  clang-analyser-*,
  cppcoreguidelines-avoid-c-arrays,
  cppcoreguidelines-special-member-functions,
  readability-*,

CheckOptions:
  - { key: readability-identifier-naming.ClassCase, value: CamelCase }
  - { key: readability-identifier-naming.FunctionCase, value: lower_case }
  - { key: readability-identifier-naming.NamespaceCase, value: lower_case }
  - { key: readability-identifier-naming.PrivateMemberPrefix, value: m_ }
  - { key: readability-identifier-naming.StructCase, value: CamelCase }
  - { key: readability-identifier-naming.VariableCase, value: lower_case }

HeaderFilterRegex: '.*'
```

The following checks match the current `argparse` style. In summary, turn off all checks, turn on all readability checks, disable some readability checks, and set options for some identifier naming.

```yaml
Checks:
  -*,
  readability-*,
  -readability-braces-around-statements,
  -readability-container-size-empty,
  -readability-else-after-return,
  -readability-function-cognitive-complexity,
  -readability-magic-numbers,
  -readability-make-member-function-const,
  -readability-named-parameter,
  -readability-qualified-auto,
  -readability-static-accessed-through-instance,

CheckOptions:
  - { key: readability-identifier-naming.ClassCase, value: CamelCase }
  - { key: readability-identifier-naming.ConstexprVariableCase, value: lower_case }
  - { key: readability-identifier-naming.FunctionCase, value: lower_case }
  - { key: readability-identifier-naming.LocalVariableIgnoredRegexp, value: "^[a-z][a-z_]+" }
  - { key: readability-identifier-naming.NamespaceCase, value: lower_case }
  - { key: readability-identifier-naming.PrivateMemberPrefix, value: m }
  - { key: readability-identifier-naming.StructCase, value: lower_case }
  - { key: readability-identifier-naming.VariableCase, value: camelBack }

HeaderFilterRegex: '.*'
```
